services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gerenciamento_usuario_db'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
